'use client'

import React from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { Section, SectionTitle, Container, Button } from '../components/UI'
import HeroBanner from '../components/HeroBanner'
import { motion } from 'framer-motion'

export default function Examinations() {
  return (
    <>
      <Navbar />
      <HeroBanner
        title="Office of the Controller of Examinations"
        subtitle="Exam Rules, Regulations, Schedules, and Results"
        cta1Text="View Results"
        cta1Link="#results"
        cta2Text="Rules & Regulations"
        cta2Link="#rules"
      />

      {/* General Information */}
      <Section className="bg-neutral-light pt-12 pb-12">
        <Container>
          <div className="bg-white rounded-xl p-8 shadow-soft">
            <h3 className="text-2xl font-bold text-primary-navy mb-6">General Information</h3>
            <ul className="space-y-4 text-gray-700">
              <li className="flex gap-3"><span className="font-bold text-primary-blue">1.</span> Every year two semester examinations are held in the month of November and April respectively.</li>
              <li className="flex gap-3"><span className="font-bold text-primary-blue">2.</span> Application for the semester examinations will be issued to the students from the Office of the Controller of Examinations (COE), through the heads of the department of our college.</li>
              <li className="flex gap-3"><span className="font-bold text-primary-blue">3.</span> Students should verify the details in the application generated by the office of the COE such as name, register number and the title of the paper and code and the same shall be submitted to the concerned HOD.</li>
              <li className="flex gap-3"><span className="font-bold text-primary-blue">4.</span> The application, signed by the student and forwarded by the Head of the Department, must be submitted to the Office of the Controller of the Examinations on or before the specified due date.</li>
              <li className="flex gap-3"><span className="font-bold text-primary-blue">5.</span> Students should pay the examination fees in Central Bank of India, K.K.Nagar Branch, Madurai-625020.</li>
              <li className="flex gap-3"><span className="font-bold text-primary-blue">6.</span> Late submission of applications will not be accepted under any circumstances.</li>
              <li className="flex gap-3"><span className="font-bold text-primary-blue">7.</span> Hall Tickets will be issued to the students by the HODs on submission of the "No Dues" Certificates obtained from the office.</li>
              <li className="flex gap-3"><span className="font-bold text-primary-blue">8.</span> It is Mandatory for the students to bring the Hall Ticket and Identity Card for all the examinations.</li>
            </ul>
          </div>
        </Container>
      </Section>

      {/* Marks Distribution */}
      <Section className="py-12">
        <Container>
          <SectionTitle title="Marks Distribution" subtitle="Theory, Practicals, and Internals" />
          
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Theory & Practical */}
            <div className="bg-white rounded-xl shadow-soft overflow-hidden border border-gray-100">
              <div className="bg-primary-navy p-4">
                <h3 className="text-xl font-bold text-white text-center">Theory & Practical Examinations</h3>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-200">
                      <th className="p-4 font-semibold text-primary-navy">Examinations</th>
                      <th className="p-4 font-semibold text-primary-navy">Level</th>
                      <th className="p-4 font-semibold text-primary-navy text-center" colSpan="2">Maximum Mark (I & E)</th>
                      <th className="p-4 font-semibold text-primary-navy text-center">Minimum Marks in External (E)</th>
                      <th className="p-4 font-semibold text-primary-navy text-center">Total Marks for Pass (I+E)</th>
                    </tr>
                    <tr className="bg-gray-50 border-b border-gray-200 text-sm">
                      <th className="p-2 border-r border-gray-200"></th>
                      <th className="p-2 border-r border-gray-200"></th>
                      <th className="p-2 text-center border-r border-gray-200">I</th>
                      <th className="p-2 text-center border-r border-gray-200">E</th>
                      <th className="p-2 text-center border-r border-gray-200"></th>
                      <th className="p-2 text-center"></th>
                    </tr>
                  </thead>
                  <tbody className="text-gray-700">
                    <tr className="border-b border-gray-100 hover:bg-gray-50">
                      <td className="p-4 font-medium" rowSpan="3">Theory</td>
                      <td className="p-4">UG</td>
                      <td className="p-4 text-center">25</td>
                      <td className="p-4 text-center">75</td>
                      <td className="p-4 text-center">-</td>
                      <td className="p-4 text-center font-bold">27 / 40</td>
                    </tr>
                    <tr className="border-b border-gray-100 hover:bg-gray-50">
                      <td className="p-4">PG</td>
                      <td className="p-4 text-center">25</td>
                      <td className="p-4 text-center">75</td>
                      <td className="p-4 text-center">-</td>
                      <td className="p-4 text-center font-bold">34 / 50</td>
                    </tr>
                    <tr className="border-b border-gray-100 hover:bg-gray-50">
                      <td className="p-4">M.Phil</td>
                      <td className="p-4 text-center">25</td>
                      <td className="p-4 text-center">75</td>
                      <td className="p-4 text-center">-</td>
                      <td className="p-4 text-center font-bold">34 / 50</td>
                    </tr>
                    <tr className="border-b border-gray-100 hover:bg-gray-50 bg-blue-50/30">
                      <td className="p-4 font-medium" rowSpan="2">Practical</td>
                      <td className="p-4">UG</td>
                      <td className="p-4 text-center">40</td>
                      <td className="p-4 text-center">60</td>
                      <td className="p-4 text-center">-</td>
                      <td className="p-4 text-center font-bold">21 / 40</td>
                    </tr>
                    <tr className="border-b border-gray-100 hover:bg-gray-50 bg-blue-50/30">
                      <td className="p-4">PG</td>
                      <td className="p-4 text-center">40</td>
                      <td className="p-4 text-center">60</td>
                      <td className="p-4 text-center">-</td>
                      <td className="p-4 text-center font-bold">27 / 50</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div className="p-4 text-sm text-gray-500 bg-gray-50 border-t border-gray-200">
                <span className="font-semibold">Note:</span> I: Internal marks | E: External marks
              </div>
            </div>

            {/* Internal Marks */}
            <div className="bg-white rounded-xl shadow-soft overflow-hidden border border-gray-100 h-fit">
              <div className="bg-primary-blue p-4">
                <h3 className="text-xl font-bold text-white text-center">Internal Marks Breakdown</h3>
              </div>
              <table className="w-full text-left border-collapse">
                <tbody className="text-gray-700 divide-y divide-gray-100">
                  <tr className="hover:bg-gray-50">
                    <td className="p-5 font-medium border-r border-gray-100 w-1/2">Test (Average of best two out of three)</td>
                    <td className="p-5 text-center text-lg font-semibold text-primary-navy">15 Marks</td>
                  </tr>
                  <tr className="hover:bg-gray-50">
                    <td className="p-5 font-medium border-r border-gray-100">Assignment</td>
                    <td className="p-5 text-center text-lg font-semibold text-primary-navy">5 Marks</td>
                  </tr>
                  <tr className="hover:bg-gray-50">
                    <td className="p-5 font-medium border-r border-gray-100">Seminar</td>
                    <td className="p-5 text-center text-lg font-semibold text-primary-navy">5 Marks</td>
                  </tr>
                  <tr className="bg-gray-50">
                    <td className="p-5 font-bold text-right text-primary-navy border-r border-gray-200">Total</td>
                    <td className="p-5 text-center text-2xl font-bold text-secondary-emerald">25 Marks</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </Container>
      </Section>

      {/* Schedule */}
      <Section className="bg-neutral-light py-12">
        <Container>
          <SectionTitle title="Schedule for Semester Examinations" subtitle="Important timelines and dates" />
          <div className="bg-white rounded-xl shadow-soft overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-primary-navy text-white">
                    <th className="p-4 font-semibold w-16 text-center">S.No.</th>
                    <th className="p-4 font-semibold">Programme / Event</th>
                    <th className="p-4 font-semibold w-1/3">Odd Semester</th>
                    <th className="p-4 font-semibold w-1/3">Even Semester</th>
                  </tr>
                </thead>
                <tbody className="text-gray-700 divide-y divide-gray-100">
                  <tr className="hover:bg-gray-50">
                    <td className="p-4 text-center font-medium">1</td>
                    <td className="p-4 font-medium">Notification of fee Collection</td>
                    <td className="p-4">First week of September</td>
                    <td className="p-4">First week of February</td>
                  </tr>
                  <tr className="hover:bg-gray-50">
                    <td className="p-4 text-center font-medium">2</td>
                    <td className="p-4">
                      <div className="font-medium">Last date for payment of fee:</div>
                      <div className="text-sm mt-1 text-gray-500">i) Without fine</div>
                      <div className="text-sm text-gray-500">ii) With fine</div>
                    </td>
                    <td className="p-4" colSpan="2">
                      <div className="mt-5 text-sm">Ten days from the date of notification</div>
                      <div className="text-sm">Five days further from the due date</div>
                    </td>
                  </tr>
                  <tr className="hover:bg-gray-50">
                    <td className="p-4 text-center font-medium">3</td>
                    <td className="p-4 font-medium">Practical Examinations</td>
                    <td className="p-4">End of October</td>
                    <td className="p-4">End of March</td>
                  </tr>
                  <tr className="hover:bg-gray-50">
                    <td className="p-4 text-center font-medium">4</td>
                    <td className="p-4 font-medium">Theory Examinations</td>
                    <td className="p-4 font-bold text-primary-blue">November</td>
                    <td className="p-4 font-bold text-primary-blue">April</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </Container>
      </Section>

      {/* Attendance Condonation */}
      <Section className="py-12">
        <Container>
          <SectionTitle title="Condonation for Attendance" subtitle="Attendance requirements to appear for exams" />
          <div className="bg-white rounded-xl shadow-soft overflow-hidden border border-gray-200">
            <table className="w-full text-left border-collapse">
              <tbody className="divide-y divide-gray-200">
                <tr className="hover:bg-gray-50">
                  <td className="p-5 font-bold text-lg text-secondary-emerald w-1/3 bg-emerald-50/30">75% of Attendance <br/><span className="text-sm font-normal text-gray-600">(out of minimum 90 working days)</span></td>
                  <td className="p-5 text-gray-800">Allowed to write examinations</td>
                </tr>
                <tr className="hover:bg-gray-50">
                  <td className="p-5 font-bold text-lg text-yellow-600 w-1/3 bg-yellow-50/30">65% to 74.99% of Attendance</td>
                  <td className="p-5 text-gray-800">Condonation fees <strong>Rs. 150</strong> along with regular examination fees</td>
                </tr>
                <tr className="hover:bg-gray-50">
                  <td className="p-5 font-bold text-lg text-orange-600 w-1/3 bg-orange-50/30">50% to 64.99% of Attendance</td>
                  <td className="p-5 text-gray-800">Condonation fees <strong>Rs. 300</strong> along with regular examination fees and along with submission of the Medical Certificate. They are eligible to appear for examinations in the next semester only.</td>
                </tr>
                <tr className="hover:bg-gray-50">
                  <td className="p-5 font-bold text-lg text-red-600 w-1/3 bg-red-50/30">Less than 50% of Attendance</td>
                  <td className="p-5 text-gray-800 font-medium">Not eligible to appear for the examination. They shall re-do semester(s) after the completion of the programme.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Container>
      </Section>

      {/* Rules and Additional Info */}
      <Section id="rules" className="bg-neutral-light py-12">
        <Container>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
            {/* Rules */}
            <div>
              <h3 className="text-2xl font-bold text-primary-navy mb-6 flex items-center gap-2">
                <span className="text-3xl">⚖️</span> Examination Rules & Regulations
              </h3>
              <div className="bg-white rounded-xl p-6 shadow-soft border-l-4 border-primary-blue">
                <ul className="space-y-4 text-gray-700">
                  <li className="flex gap-3 items-start"><span className="text-primary-blue mt-1">•</span> Students without hall ticket and identity card will not be permitted for any examination.</li>
                  <li className="flex gap-3 items-start"><span className="text-primary-blue mt-1">•</span> Possession of materials and any form of copying is prohibited inside the examination hall.</li>
                  <li className="flex gap-3 items-start"><span className="text-primary-blue mt-1">•</span> Students indulging in any form of malpractice in the examination are liable to severe punishment.</li>
                  <li className="flex gap-3 items-start"><span className="text-primary-blue mt-1">•</span> Students will not be permitted into the examination hall after 30 minutes from the time of commencement of examination.</li>
                  <li className="flex gap-3 items-start"><span className="text-primary-blue mt-1">•</span> Students should not write their names or any other identification marking, except their register number in the answer scripts.</li>
                  <li className="flex gap-3 items-start"><span className="text-primary-blue mt-1">•</span> Students should maintain pin drop silence in the examination hall.</li>
                  <li className="flex gap-3 items-start"><span className="text-primary-blue mt-1">•</span> Students should bring their own requirements like Pen, Pencil, Calculator for the examination, and should not borrow from others.</li>
                  <li className="flex gap-3 items-start"><span className="text-primary-blue mt-1">•</span> The students should come in formal dress.</li>
                </ul>
              </div>
            </div>

            {/* Other Policies */}
            <div className="space-y-8">
              <div>
                <h3 className="text-2xl font-bold text-primary-navy mb-4 flex items-center gap-2">
                  <span className="text-3xl">📝</span> External Valuation & Results
                </h3>
                <div className="bg-white rounded-xl p-6 shadow-soft">
                  <h4 className="font-bold text-lg mb-2 text-primary-navy">External Valuation Systems</h4>
                  <p className="text-gray-700 mb-6">Single valuation by the external examiners for all the courses is followed.</p>
                  
                  <h4 className="font-bold text-lg mb-2 text-primary-navy">Declaration of Results</h4>
                  <p className="text-gray-700">Results will be placed in passing board and declared only after getting approval from the awards committee consisting of nominees from Madurai Kamaraj University, Principal, COE and Heads of the department. The results will be published within 20 days from the date of completion of examination. The results will be displayed in the notice board and also uploaded in the college website.</p>
                </div>
              </div>

              <div>
                <h3 className="text-2xl font-bold text-primary-navy mb-4 flex items-center gap-2">
                  <span className="text-3xl">🔄</span> Reappearing Candidates
                </h3>
                <div className="bg-white rounded-xl p-6 shadow-soft">
                  <p className="text-gray-700 mb-4">A student who has arrears in any paper in a semester examination will be permitted to attend the next semester. A student who has arrears in paper / papers of that semester examinations may appear again in these failed papers in the next examinations. The Internal Assessment marks already obtained by him/her shall be carried over.</p>
                  <p className="text-gray-700 mb-4">A student who fails in any theory paper will be allowed to re-appear for that paper in the succeeding examinations under the same syllabus, only for a period of 5 years, from his date of joining. Beyond that the candidate has to reappear only in the latest revised syllabus, and he has to prepare for that new syllabus on his own. He can be allowed only to write that particular examinations, and he could obtain the degree. In case he needs any equivalence he will be given after placing it to the experts.</p>
                  <p className="text-gray-700 bg-blue-50 p-4 rounded-lg border border-blue-100"><strong className="text-primary-navy">Supplementary Examinations:</strong> Shall be conducted immediately after publishing the final semester results. Those students who have failed in the examination, shall be permitted to appear for two papers in the supplementary examination (one paper from the final semester, any one paper from any other previous semester).</p>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </Section>

      {/* Results Check Form */}
      <Section id="results" className="pt-12 pb-20">
        <Container>
          <SectionTitle title="Check Results Online" subtitle="View your examination results quickly" />
          <div className="max-w-2xl mx-auto bg-white rounded-xl p-8 shadow-elevated border-t-4 border-primary-blue">
            <form className="space-y-6">
              <div>
                <label className="block text-sm font-semibold text-primary-navy mb-2">
                  Registration Number
                </label>
                <input
                  type="text"
                  placeholder="Enter your registration number"
                  className="w-full px-4 py-3 border border-neutral-gray rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-blue bg-gray-50"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-primary-navy mb-2">
                  Semester
                </label>
                <select className="w-full px-4 py-3 border border-neutral-gray rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-blue bg-gray-50">
                  <option>Select Semester</option>
                  <option>Semester I</option>
                  <option>Semester II</option>
                  <option>Semester III</option>
                  <option>Semester IV</option>
                  <option>Semester V</option>
                  <option>Semester VI</option>
                </select>
              </div>
              <Button variant="primary" size="lg" className="w-full shadow-md hover:shadow-lg">
                View Results
              </Button>
            </form>
          </div>
        </Container>
      </Section>

      <Footer />
    </>
  )
}
