export const courses = [
  {
    slug: 'bsc-computer-science',
    name: 'B.Sc. Computer Science',
    degree: 'Bachelor of Science',
    department: 'Computer Science & Engineering',
    duration: '3 Years',
    type: 'Undergraduate',
    mode: 'Full-Time',
    seats: 60,
    fee: '₹45,000 / year',
    eligibility: '12th with Mathematics & Science (Min. 50%)',
    affiliation: 'Madurai Kamaraj University',
    accreditation: 'NAAC Grade A',
    overview:
      'The B.Sc. Computer Science program equips students with a strong foundation in programming, algorithms, data structures, and software engineering. Graduates are prepared for careers in software development, data science, and IT management.',
    highlights: [
      'Industry-aligned curriculum updated annually',
      'Dedicated programming labs with 24/7 access',
      'Internship tie-ups with 50+ IT companies',
      'Project-based learning in every semester',
      'Expert guest lectures from industry professionals',
      'Placement assistance with 95%+ record',
    ],
    curriculum: [
      {
        semester: 'Semester I',
        subjects: ['Programming in C', 'Mathematics I', 'Digital Electronics', 'English Communication', 'Environmental Science'],
      },
      {
        semester: 'Semester II',
        subjects: ['Data Structures', 'Mathematics II', 'Object-Oriented Programming (Java)', 'Database Management Systems', 'Web Technologies'],
      },
      {
        semester: 'Semester III',
        subjects: ['Operating Systems', 'Computer Networks', 'Software Engineering', 'Python Programming', 'Discrete Mathematics'],
      },
      {
        semester: 'Semester IV',
        subjects: ['Algorithms & Complexity', 'Artificial Intelligence', 'Mobile Application Development', 'Cloud Computing', 'Mini Project'],
      },
      {
        semester: 'Semester V',
        subjects: ['Machine Learning', 'Cyber Security', 'Big Data Analytics', 'Elective I', 'Internship'],
      },
      {
        semester: 'Semester VI',
        subjects: ['Deep Learning', 'IoT & Embedded Systems', 'Elective II', 'Major Project', 'Entrepreneurship'],
      },
    ],
    faculty: [
      { name: 'Dr. A. Rajkumar', designation: 'Head of Department', qualification: 'Ph.D. Computer Science' },
      { name: 'Prof. S. Meenakshi', designation: 'Associate Professor', qualification: 'M.Tech, NET' },
      { name: 'Dr. K. Venkatesh', designation: 'Assistant Professor', qualification: 'Ph.D. AI & ML' },
      { name: 'Prof. R. Priya', designation: 'Assistant Professor', qualification: 'M.Sc. CS, SET' },
    ],
    careerProspects: [
      'Software Developer / Engineer',
      'Data Scientist / Analyst',
      'Web & Mobile App Developer',
      'System Administrator',
      'Cybersecurity Analyst',
      'AI / ML Engineer',
      'Database Administrator',
      'IT Consultant',
    ],
    topRecruiters: ['TCS', 'Infosys', 'Wipro', 'HCL', 'Cognizant', 'Zoho', 'Freshworks', 'Amazon'],
    color: 'from-blue-600 to-cyan-500',
    icon: '💻',
  },
  {
    slug: 'bcom',
    name: 'B.Com.',
    degree: 'Bachelor of Commerce',
    department: 'Commerce & Business Administration',
    duration: '3 Years',
    type: 'Undergraduate',
    mode: 'Full-Time',
    seats: 80,
    fee: '₹30,000 / year',
    eligibility: '12th with Commerce / Any Stream (Min. 45%)',
    affiliation: 'Madurai Kamaraj University',
    accreditation: 'NAAC Grade A',
    overview:
      'The B.Com. program provides comprehensive knowledge of accounting, finance, taxation, and business law. It prepares students for careers in banking, finance, auditing, and entrepreneurship.',
    highlights: [
      'Strong focus on practical accounting & taxation',
      'CA / CMA / CS foundation integration',
      'Industry visits to banks and financial firms',
      'Tally ERP & GST certification included',
      'Mock stock market trading sessions',
      'Placement support with leading banks & firms',
    ],
    curriculum: [
      {
        semester: 'Semester I',
        subjects: ['Financial Accounting', 'Business Economics', 'Business Mathematics', 'English', 'Business Communication'],
      },
      {
        semester: 'Semester II',
        subjects: ['Advanced Accounting', 'Business Law', 'Statistics', 'Banking Theory', 'Computer Applications'],
      },
      {
        semester: 'Semester III',
        subjects: ['Corporate Accounting', 'Income Tax', 'Cost Accounting', 'Business Management', 'Auditing'],
      },
      {
        semester: 'Semester IV',
        subjects: ['Financial Management', 'GST & Indirect Tax', 'Management Accounting', 'Company Law', 'E-Commerce'],
      },
      {
        semester: 'Semester V',
        subjects: ['Investment Management', 'International Trade', 'Elective I', 'Project Work', 'Entrepreneurship'],
      },
      {
        semester: 'Semester VI',
        subjects: ['Strategic Management', 'Insurance & Risk', 'Elective II', 'Major Project', 'Soft Skills'],
      },
    ],
    faculty: [
      { name: 'Dr. P. Sundaram', designation: 'Head of Department', qualification: 'Ph.D. Commerce' },
      { name: 'Prof. L. Kavitha', designation: 'Associate Professor', qualification: 'M.Com, NET' },
      { name: 'Dr. M. Anand', designation: 'Assistant Professor', qualification: 'Ph.D. Finance' },
      { name: 'Prof. T. Selvi', designation: 'Assistant Professor', qualification: 'M.Com, SET' },
    ],
    careerProspects: [
      'Chartered Accountant (CA)',
      'Company Secretary (CS)',
      'Bank Officer / Manager',
      'Financial Analyst',
      'Tax Consultant',
      'Auditor',
      'Business Analyst',
      'Entrepreneur',
    ],
    topRecruiters: ['SBI', 'HDFC Bank', 'ICICI Bank', 'Deloitte', 'KPMG', 'EY', 'PWC', 'Axis Bank'],
    color: 'from-emerald-600 to-teal-500',
    icon: '📊',
  },
  {
    slug: 'ba-english',
    name: 'B.A. English',
    degree: 'Bachelor of Arts',
    department: 'Humanities & Social Sciences',
    duration: '3 Years',
    type: 'Undergraduate',
    mode: 'Full-Time',
    seats: 60,
    fee: '₹25,000 / year',
    eligibility: '12th in Any Stream (Min. 45%)',
    affiliation: 'Madurai Kamaraj University',
    accreditation: 'NAAC Grade A',
    overview:
      'The B.A. English program develops critical thinking, communication, and literary analysis skills. Students explore literature, linguistics, and creative writing, preparing for careers in education, media, and content creation.',
    highlights: [
      'Rich literary curriculum spanning world literature',
      'Creative writing workshops every semester',
      'Journalism & media studies integration',
      'Language lab with advanced tools',
      'Annual literary festival & competitions',
      'Strong alumni network in media & education',
    ],
    curriculum: [
      { semester: 'Semester I', subjects: ['Prose & Fiction', 'Grammar & Composition', 'Indian Writing in English', 'Tamil / Second Language', 'Soft Skills'] },
      { semester: 'Semester II', subjects: ['Poetry', 'Drama', 'Linguistics', 'Communication Skills', 'Environmental Studies'] },
      { semester: 'Semester III', subjects: ['British Literature', 'American Literature', 'Phonetics', 'Creative Writing', 'Journalism Basics'] },
      { semester: 'Semester IV', subjects: ['Post-Colonial Literature', 'Literary Criticism', 'Translation Studies', 'Media Writing', 'Elective I'] },
      { semester: 'Semester V', subjects: ['World Literature', 'Research Methodology', 'Content Writing', 'Elective II', 'Internship'] },
      { semester: 'Semester VI', subjects: ['Contemporary Literature', 'Dissertation', 'Digital Media', 'Elective III', 'Viva Voce'] },
    ],
    faculty: [
      { name: 'Dr. S. Lakshmi', designation: 'Head of Department', qualification: 'Ph.D. English Literature' },
      { name: 'Prof. N. Bharathi', designation: 'Associate Professor', qualification: 'M.A. English, NET' },
      { name: 'Dr. V. Rajan', designation: 'Assistant Professor', qualification: 'Ph.D. Linguistics' },
      { name: 'Prof. G. Deepa', designation: 'Assistant Professor', qualification: 'M.A. English, SET' },
    ],
    careerProspects: ['Content Writer / Editor', 'Journalist', 'Teacher / Lecturer', 'Translator', 'PR Executive', 'Copywriter', 'Civil Services', 'Author'],
    topRecruiters: ['The Hindu', 'Times of India', 'Penguin Books', 'BYJU\'S', 'Unacademy', 'Govt. Schools', 'Content Agencies', 'NGOs'],
    color: 'from-purple-600 to-pink-500',
    icon: '📚',
  },
  {
    slug: 'mba',
    name: 'M.B.A.',
    degree: 'Master of Business Administration',
    department: 'Management',
    duration: '2 Years',
    type: 'Postgraduate',
    mode: 'Full-Time',
    seats: 60,
    fee: '₹85,000 / year',
    eligibility: "Any Bachelor's Degree (Min. 50%) + Entrance Exam",
    affiliation: 'Madurai Kamaraj University',
    accreditation: 'NAAC Grade A | AICTE Approved',
    overview:
      'The MBA program at MISS College develops future business leaders with strong analytical, strategic, and leadership skills. With specializations in Finance, Marketing, HR, and Operations, graduates are industry-ready from day one.',
    highlights: [
      'AICTE approved 2-year full-time program',
      'Dual specialization available',
      'Live industry projects every semester',
      'International case study methodology',
      'Leadership development bootcamps',
      '100% placement assistance',
    ],
    curriculum: [
      { semester: 'Semester I', subjects: ['Management Principles', 'Managerial Economics', 'Financial Accounting', 'Organizational Behaviour', 'Business Statistics', 'Business Communication'] },
      { semester: 'Semester II', subjects: ['Marketing Management', 'Financial Management', 'Human Resource Management', 'Operations Management', 'Business Research Methods', 'IT for Managers'] },
      { semester: 'Semester III', subjects: ['Strategic Management', 'Specialization I', 'Specialization II', 'Specialization III', 'Summer Internship Report', 'Elective I'] },
      { semester: 'Semester IV', subjects: ['Entrepreneurship & Innovation', 'Specialization IV', 'Specialization V', 'Elective II', 'Major Project', 'Viva Voce'] },
    ],
    faculty: [
      { name: 'Dr. R. Krishnamurthy', designation: 'Director, MBA', qualification: 'Ph.D. Management, IIM Alumni' },
      { name: 'Prof. A. Saraswathi', designation: 'Professor – Marketing', qualification: 'MBA, Ph.D.' },
      { name: 'Dr. B. Senthil', designation: 'Professor – Finance', qualification: 'Ph.D. Finance, CFA' },
      { name: 'Prof. C. Nirmala', designation: 'Professor – HR', qualification: 'MBA HR, NET' },
    ],
    careerProspects: ['Business Manager', 'Marketing Manager', 'Financial Analyst', 'HR Manager', 'Operations Manager', 'Consultant', 'Entrepreneur', 'Product Manager'],
    topRecruiters: ['Amazon', 'Flipkart', 'Deloitte', 'Accenture', 'HDFC Bank', 'Asian Paints', 'ITC', 'Mahindra'],
    color: 'from-amber-500 to-orange-500',
    icon: '🎓',
  },
  {
    slug: 'msc-computer-science',
    name: 'M.Sc. Computer Science',
    degree: 'Master of Science',
    department: 'Computer Science & Engineering',
    duration: '2 Years',
    type: 'Postgraduate',
    mode: 'Full-Time',
    seats: 30,
    fee: '₹55,000 / year',
    eligibility: 'B.Sc. CS / BCA / B.Tech (Min. 50%)',
    affiliation: 'Madurai Kamaraj University',
    accreditation: 'NAAC Grade A',
    overview:
      'The M.Sc. Computer Science program offers advanced training in AI, machine learning, cloud computing, and research methodologies. It prepares students for research careers, higher studies, and senior technical roles.',
    highlights: [
      'Advanced AI & ML specialization track',
      'Research publication support',
      'Industry-sponsored capstone projects',
      'Access to HPC computing cluster',
      'Ph.D. pathway guidance',
      'International conference participation support',
    ],
    curriculum: [
      { semester: 'Semester I', subjects: ['Advanced Algorithms', 'Advanced DBMS', 'Machine Learning', 'Research Methodology', 'Elective I'] },
      { semester: 'Semester II', subjects: ['Deep Learning', 'Cloud & Distributed Computing', 'Natural Language Processing', 'Elective II', 'Mini Project'] },
      { semester: 'Semester III', subjects: ['Computer Vision', 'Blockchain Technology', 'Elective III', 'Elective IV', 'Internship / Research'] },
      { semester: 'Semester IV', subjects: ['Advanced Cyber Security', 'Elective V', 'Major Research Project', 'Seminar', 'Viva Voce'] },
    ],
    faculty: [
      { name: 'Dr. A. Rajkumar', designation: 'Head of Department', qualification: 'Ph.D. Computer Science' },
      { name: 'Dr. K. Venkatesh', designation: 'Associate Professor', qualification: 'Ph.D. AI & ML' },
      { name: 'Prof. D. Harini', designation: 'Assistant Professor', qualification: 'M.Tech CS, NET' },
      { name: 'Dr. E. Suresh', designation: 'Assistant Professor', qualification: 'Ph.D. Cloud Computing' },
    ],
    careerProspects: ['AI / ML Engineer', 'Research Scientist', 'Data Engineer', 'Cloud Architect', 'Ph.D. Scholar', 'Software Architect', 'Cybersecurity Expert', 'University Lecturer'],
    topRecruiters: ['Google', 'Microsoft', 'IBM', 'Oracle', 'TCS Research', 'ISRO', 'DRDO', 'IITs'],
    color: 'from-indigo-600 to-blue-500',
    icon: '🔬',
  },
]

export function getCourse(slug) {
  return courses.find((c) => c.slug === slug) || null
}
